// Generated from packages/native/include/opentui.h. Run bun run generate:abi in packages/core.
pub const OT_CONTEXT_ABI_VERSION: u32 = 1;
pub const OT_OK: i32 = 0;
pub const OT_INVALID_ARGUMENT: i32 = -1;
pub const OT_UNSUPPORTED_VERSION: i32 = -2;
pub const OT_OUT_OF_MEMORY: i32 = -3;
pub const OT_WRONG_THREAD: i32 = -4;
pub const OT_INTERNAL_ERROR: i32 = -5;
pub const OT_CONTEXT_BUSY: i32 = -6;
pub const OT_WRONG_CONTEXT: i32 = -7;
pub const OT_WRONG_KIND: i32 = -8;
pub const OT_STALE_HANDLE: i32 = -9;
pub const OT_WRONG_SESSION: i32 = -10;
pub const OT_OUTPUT_BACKPRESSURE: i32 = -11;
pub const OT_SESSION_CLOSED: i32 = -12;
pub const OT_OUTPUT_BUSY: i32 = -13;
pub const OT_STALE_OUTPUT: i32 = -14;
pub const OT_OUTPUT_FAILED: i32 = -15;
pub const OT_OBJECT_LIMIT: i32 = -16;
pub const OT_RENDERER_ATTACHED: i32 = -17;
pub const OT_RENDERER_NOT_ATTACHED: i32 = -18;
pub const OT_INVALID_PHASE: i32 = -19;
pub const OT_CONTROL_PACKET_LIMIT: i32 = -20;
pub const OT_LEASE_LIMIT: i32 = -21;
pub const OT_LEASE_BYTES_LIMIT: i32 = -22;
pub const OT_STALE_LEASE: i32 = -23;
pub const OT_UNSUPPORTED_RESOURCE: i32 = -24;
pub const OT_STALE_FRAME: i32 = -25;
pub const OT_LAYOUT_LIMIT: i32 = -26;
pub const OT_FRAME_BUSY: i32 = -27;
pub const OT_FRAME_REQUEST_LIMIT: i32 = -28;
pub const OT_SCENE_ROOT: u32 = 0;
pub const OT_SCENE_BOX: u32 = 1;
pub const OT_SCENE_TEXT: u32 = 2;
pub const OT_SCENE_SLIDER: u32 = 3;
pub const OT_SCENE_ARROW: u32 = 4;
pub const OT_SCENE_EDITOR: u32 = 5;
pub const OT_SCENE_CUSTOM: u32 = 6;
pub const OT_SCENE_TEXT_VIEW: u32 = 7;
pub const OT_SCENE_IMAGE: u32 = 8;
pub const OT_SCENE_WRAP_NONE: u32 = 0;
pub const OT_SCENE_WRAP_CHAR: u32 = 1;
pub const OT_SCENE_WRAP_WORD: u32 = 2;
pub const OT_STYLE_ENUM: u32 = 0;
pub const OT_STYLE_FLOAT: u32 = 1;
pub const OT_STYLE_VALUE: u32 = 2;
pub const OT_STYLE_BORDER: u32 = 3;
pub const OT_STYLE_DIMENSION: u32 = 4;
pub const OT_STYLE_BORDER_WIDTH: u32 = 0;
pub const OT_STYLE_FLAGS_NONE: u32 = 0;
pub const OT_STYLE_DISABLE_FLEX_SHRINK: u32 = 1;
pub const OT_STYLE_ENUM_DIRECTION: u32 = 0;
pub const OT_STYLE_ENUM_FLEX_DIRECTION: u32 = 1;
pub const OT_STYLE_ENUM_JUSTIFY_CONTENT: u32 = 2;
pub const OT_STYLE_ENUM_ALIGN_CONTENT: u32 = 3;
pub const OT_STYLE_ENUM_ALIGN_ITEMS: u32 = 4;
pub const OT_STYLE_ENUM_ALIGN_SELF: u32 = 5;
pub const OT_STYLE_ENUM_POSITION_TYPE: u32 = 6;
pub const OT_STYLE_ENUM_FLEX_WRAP: u32 = 7;
pub const OT_STYLE_ENUM_OVERFLOW: u32 = 8;
pub const OT_STYLE_ENUM_DISPLAY: u32 = 9;
pub const OT_STYLE_ENUM_BOX_SIZING: u32 = 10;
pub const OT_STYLE_FLOAT_FLEX: u32 = 0;
pub const OT_STYLE_FLOAT_FLEX_GROW: u32 = 1;
pub const OT_STYLE_FLOAT_FLEX_SHRINK: u32 = 2;
pub const OT_STYLE_FLOAT_ASPECT_RATIO: u32 = 3;
pub const OT_STYLE_VALUE_WIDTH: u32 = 0;
pub const OT_STYLE_VALUE_HEIGHT: u32 = 1;
pub const OT_STYLE_VALUE_MIN_WIDTH: u32 = 2;
pub const OT_STYLE_VALUE_MIN_HEIGHT: u32 = 3;
pub const OT_STYLE_VALUE_MAX_WIDTH: u32 = 4;
pub const OT_STYLE_VALUE_MAX_HEIGHT: u32 = 5;
pub const OT_STYLE_VALUE_FLEX_BASIS: u32 = 6;
pub const OT_STYLE_VALUE_MARGIN: u32 = 7;
pub const OT_STYLE_VALUE_PADDING: u32 = 8;
pub const OT_STYLE_VALUE_POSITION: u32 = 9;
pub const OT_STYLE_VALUE_GAP: u32 = 10;
pub const OT_DIMENSION_WIDTH: u32 = 0;
pub const OT_DIMENSION_HEIGHT: u32 = 1;
pub const OT_UNIT_UNDEFINED: u32 = 0;
pub const OT_UNIT_POINT: u32 = 1;
pub const OT_UNIT_PERCENT: u32 = 2;
pub const OT_UNIT_AUTO: u32 = 3;
pub const OT_EDGE_NONE: u32 = 0;
pub const OT_EDGE_LEFT: u32 = 0;
pub const OT_EDGE_TOP: u32 = 1;
pub const OT_EDGE_RIGHT: u32 = 2;
pub const OT_EDGE_BOTTOM: u32 = 3;
pub const OT_EDGE_START: u32 = 4;
pub const OT_EDGE_END: u32 = 5;
pub const OT_EDGE_HORIZONTAL: u32 = 6;
pub const OT_EDGE_VERTICAL: u32 = 7;
pub const OT_EDGE_ALL: u32 = 8;
pub const OT_GUTTER_COLUMN: u32 = 0;
pub const OT_GUTTER_ROW: u32 = 1;
pub const OT_GUTTER_ALL: u32 = 2;
pub const OT_DIRECTION_INHERIT: u32 = 0;
pub const OT_DIRECTION_LTR: u32 = 1;
pub const OT_DIRECTION_RTL: u32 = 2;
pub const OT_FLEX_DIRECTION_COLUMN: u32 = 0;
pub const OT_FLEX_DIRECTION_COLUMN_REVERSE: u32 = 1;
pub const OT_FLEX_DIRECTION_ROW: u32 = 2;
pub const OT_FLEX_DIRECTION_ROW_REVERSE: u32 = 3;
pub const OT_JUSTIFY_FLEX_START: u32 = 0;
pub const OT_JUSTIFY_CENTER: u32 = 1;
pub const OT_JUSTIFY_FLEX_END: u32 = 2;
pub const OT_JUSTIFY_SPACE_BETWEEN: u32 = 3;
pub const OT_JUSTIFY_SPACE_AROUND: u32 = 4;
pub const OT_JUSTIFY_SPACE_EVENLY: u32 = 5;
pub const OT_ALIGN_AUTO: u32 = 0;
pub const OT_ALIGN_FLEX_START: u32 = 1;
pub const OT_ALIGN_CENTER: u32 = 2;
pub const OT_ALIGN_FLEX_END: u32 = 3;
pub const OT_ALIGN_STRETCH: u32 = 4;
pub const OT_ALIGN_BASELINE: u32 = 5;
pub const OT_ALIGN_SPACE_BETWEEN: u32 = 6;
pub const OT_ALIGN_SPACE_AROUND: u32 = 7;
pub const OT_ALIGN_SPACE_EVENLY: u32 = 8;
pub const OT_POSITION_STATIC: u32 = 0;
pub const OT_POSITION_RELATIVE: u32 = 1;
pub const OT_POSITION_ABSOLUTE: u32 = 2;
pub const OT_FLEX_WRAP_NONE: u32 = 0;
pub const OT_FLEX_WRAP_WRAP: u32 = 1;
pub const OT_FLEX_WRAP_REVERSE: u32 = 2;
pub const OT_OVERFLOW_VISIBLE: u32 = 0;
pub const OT_OVERFLOW_HIDDEN: u32 = 1;
pub const OT_OVERFLOW_SCROLL: u32 = 2;
pub const OT_DISPLAY_FLEX: u32 = 0;
pub const OT_DISPLAY_NONE: u32 = 1;
pub const OT_BOX_SIZING_BORDER_BOX: u32 = 0;
pub const OT_BOX_SIZING_CONTENT_BOX: u32 = 1;
pub const OT_STYLE_ENUM_DIRECTION_MAX: u32 = 2;
pub const OT_STYLE_ENUM_FLEX_DIRECTION_MAX: u32 = 3;
pub const OT_STYLE_ENUM_JUSTIFY_CONTENT_MAX: u32 = 5;
pub const OT_STYLE_ENUM_ALIGN_CONTENT_MAX: u32 = 8;
pub const OT_STYLE_ENUM_ALIGN_ITEMS_MAX: u32 = 8;
pub const OT_STYLE_ENUM_ALIGN_SELF_MAX: u32 = 8;
pub const OT_STYLE_ENUM_POSITION_TYPE_MAX: u32 = 2;
pub const OT_STYLE_ENUM_FLEX_WRAP_MAX: u32 = 2;
pub const OT_STYLE_ENUM_OVERFLOW_MAX: u32 = 2;
pub const OT_STYLE_ENUM_DISPLAY_MAX: u32 = 1;
pub const OT_STYLE_ENUM_BOX_SIZING_MAX: u32 = 1;
pub const OT_MEASURE_UNDEFINED: u32 = 0;
pub const OT_MEASURE_EXACTLY: u32 = 1;
pub const OT_MEASURE_AT_MOST: u32 = 2;
pub const OT_LAYOUT_PUBLIC: u32 = 0;
pub const OT_LAYOUT_YOGA: u32 = 1;
pub const OT_LAYOUT_PAINT: u32 = 2;
pub const OT_BORDER_NONE: u32 = 0;
pub const OT_BORDER_LEFT: u32 = 1;
pub const OT_BORDER_BOTTOM: u32 = 2;
pub const OT_BORDER_RIGHT: u32 = 4;
pub const OT_BORDER_TOP: u32 = 8;
pub const OT_BORDER_ALL: u32 = 15;
pub const OT_BORDER_SINGLE: u32 = 0;
pub const OT_BORDER_DOUBLE: u32 = 1;
pub const OT_BORDER_ROUNDED: u32 = 2;
pub const OT_BORDER_HEAVY: u32 = 3;
pub const OT_COLOR_RGB: u32 = 0;
pub const OT_COLOR_INDEXED: u32 = 1;
pub const OT_COLOR_DEFAULT: u32 = 2;
pub const OT_COLOR_CHANNEL_MASK: u32 = 255;
pub const OT_COLOR_META_SHIFT: u32 = 8;
pub const OT_SCENE_TEXT_SELECTION_RESET: u32 = 0;
pub const OT_SCENE_TEXT_SELECTION_SET: u32 = 1;
pub const OT_SCENE_TEXT_SELECTION_UPDATE: u32 = 2;
pub const OT_SCENE_TEXT_SELECTION_CELL: u32 = 0;
pub const OT_SCENE_TEXT_SELECTION_WORD: u32 = 1;
pub const OT_SCENE_TEXT_SELECTION_LINE: u32 = 2;
pub const OT_SCENE_TEXT_SELECTION_BACKGROUND: u32 = 1;
pub const OT_SCENE_TEXT_SELECTION_FOREGROUND: u32 = 2;
pub const OT_SCENE_TEXT_FOREGROUND: u32 = 1;
pub const OT_SCENE_TEXT_BACKGROUND: u32 = 2;
pub const OT_SCENE_TEXT_LINK: u32 = 4;
pub const OT_SCENE_MUTATIONS_MAX: u32 = 4096;
pub const OT_SCENE_HOOK_UPDATE: u32 = 1;
pub const OT_SCENE_HOOK_RESIZE: u32 = 2;
pub const OT_SCENE_HOOK_LAYOUT_CHANGED: u32 = 4;
pub const OT_SCENE_HOOK_RENDER_BEFORE: u32 = 8;
pub const OT_SCENE_HOOK_RENDER_AFTER: u32 = 16;
pub const OT_SCENE_HOOK_RENDER_SELF: u32 = 32;
pub const OT_SCENE_HOOK_IDLE_UPDATE: u32 = 64;
pub const OT_SCENE_HOOK_RESUME_NATIVE_TEXT: u32 = 128;
pub const OT_SCENE_FRAME_DONE: u32 = 0;
pub const OT_SCENE_FRAME_UPDATE: u32 = 1;
pub const OT_SCENE_FRAME_RESIZE: u32 = 2;
pub const OT_SCENE_FRAME_LAYOUT_CHANGED: u32 = 3;
pub const OT_SCENE_FRAME_RENDER_BEFORE: u32 = 4;
pub const OT_SCENE_FRAME_RENDER_AFTER: u32 = 5;
pub const OT_SCENE_FRAME_YIELD: u32 = 6;
pub const OT_SCENE_FRAME_RENDER_SELF: u32 = 7;
pub const OT_SCENE_GEOMETRY_PAINT: u32 = 1;
pub const OT_SCENE_GEOMETRY_PUBLIC: u32 = 2;
pub const OT_SCENE_UPDATE_SKIP: u32 = 0;
pub const OT_SCENE_UPDATE_APPLY: u32 = 1;
pub const OT_SESSION_OPEN: u32 = 0;
pub const OT_SESSION_CLOSING: u32 = 1;
pub const OT_SESSION_CLOSED_STATE: u32 = 2;
pub const OT_SESSION_FAILED: u32 = 3;
pub const OT_SESSION_CANCELLED_STATE: u32 = 4;
pub const OT_SESSION_REMOTE_AUTO: u32 = 0;
pub const OT_SESSION_REMOTE_LOCAL: u32 = 1;
pub const OT_SESSION_REMOTE_REMOTE: u32 = 2;
pub const OT_SESSION_ENV_ENTRIES_MAX: u32 = 256;
pub const OT_SESSION_ENV_BYTES_MAX: u32 = 65536;
pub const OT_RENDER_PRESENTED: u32 = 0;
pub const OT_RENDER_PENDING: u32 = 1;
pub const OT_RENDER_SKIPPED: u32 = 2;
pub const OT_RENDER_FAILED: u32 = 3;
pub const OT_SESSION_BUFFER_CURRENT: u32 = 0;
pub const OT_SESSION_BUFFER_NEXT: u32 = 1;
pub const OT_WIDTH_METHOD_WCWIDTH: u32 = 0;
pub const OT_WIDTH_METHOD_UNICODE: u32 = 1;
pub const OT_WIDTH_METHOD_NO_ZWJ: u32 = 2;
pub const OT_WIDTH_METHOD_UNICODE_WIDE: u32 = 3;
pub const OT_BUFFER_RESPECT_ALPHA: u32 = 1;
pub const OT_EMBEDDED_TERMINAL_INVALIDATE: u32 = 0;
pub const OT_EMBEDDED_TERMINAL_SCROLL: u32 = 1;
pub const OT_EMBEDDED_TERMINAL_CLEAR_SELECTION: u32 = 2;
pub const OT_EDIT_CURSOR_CHANGED: u32 = 1;
pub const OT_EDIT_CONTENT_CHANGED: u32 = 2;
pub const OT_EDIT_HISTORY_CURSOR_CHANGED: u32 = 4;
pub const OT_EDIT_DELETE_FORWARD: u32 = 0;
pub const OT_EDIT_BACKSPACE: u32 = 1;
pub const OT_EDIT_NEW_LINE: u32 = 2;
pub const OT_EDIT_DELETE_LINE: u32 = 3;
pub const OT_EDIT_MOVE_LEFT: u32 = 4;
pub const OT_EDIT_MOVE_RIGHT: u32 = 5;
pub const OT_EDIT_MOVE_UP: u32 = 6;
pub const OT_EDIT_MOVE_DOWN: u32 = 7;
pub const OT_EDIT_GOTO_LINE: u32 = 8;
pub const OT_EDIT_CURSOR_OFFSET: u32 = 9;
pub const OT_EDIT_CLEAR: u32 = 10;
pub const OT_EDIT_CLEAR_HISTORY: u32 = 11;
pub const OT_EDIT_DEBUG_ROPE: u32 = 12;
pub const OT_EDIT_POSITION_CURSOR: u32 = 0;
pub const OT_EDIT_POSITION_NEXT_WORD: u32 = 1;
pub const OT_EDIT_POSITION_PREV_WORD: u32 = 2;
pub const OT_EDIT_POSITION_EOL: u32 = 3;
pub const OT_EDIT_POSITION_OFFSET: u32 = 4;
pub const OT_EDIT_POSITION_COORDS: u32 = 5;
pub const OT_EDIT_POSITION_LINE_START: u32 = 6;
pub const OT_EDITOR_STYLE_FOREGROUND: u32 = 1;
pub const OT_EDITOR_STYLE_BACKGROUND: u32 = 2;
pub const OT_EDITOR_STYLE_ATTRIBUTES: u32 = 4;
pub const OT_EDIT_HIGHLIGHT_ADD_LINE: u32 = 0;
pub const OT_EDIT_HIGHLIGHT_ADD_RANGE: u32 = 1;
pub const OT_EDIT_HIGHLIGHT_REMOVE_REF: u32 = 2;
pub const OT_EDIT_HIGHLIGHT_CLEAR_LINE: u32 = 3;
pub const OT_EDIT_HIGHLIGHT_CLEAR_ALL: u32 = 4;
pub const OT_EDITOR_MOVE_UP: u32 = 0;
pub const OT_EDITOR_MOVE_DOWN: u32 = 1;
pub const OT_EDITOR_GOTO_LINE_END: u32 = 2;
pub const OT_EDITOR_DELETE_SELECTION: u32 = 3;
pub const OT_EDITOR_CURSOR_OFFSET: u32 = 4;
pub const OT_EDITOR_WRAP_MODE: u32 = 5;
pub const OT_EDITOR_TAB_INDICATOR: u32 = 6;
pub const OT_EDITOR_SELECT_SET: u32 = 0;
pub const OT_EDITOR_SELECT_UPDATE: u32 = 1;
pub const OT_EDITOR_SELECT_RESET: u32 = 2;
pub const OT_EDITOR_SELECT_LOCAL: u32 = 3;
pub const OT_EDITOR_SELECT_LOCAL_UPDATE: u32 = 4;
pub const OT_EDITOR_SELECT_LOCAL_RESET: u32 = 5;
pub const OT_EDITOR_SELECT_CELL: u32 = 6;
pub const OT_EDITOR_SELECT_OCCUPANCY: u32 = 7;
pub const OT_EDITOR_SELECT_INCLUSIVE: u32 = 8;
pub const OT_EDITOR_SELECT_COLORS: u32 = 9;
pub const OT_SELECT_DOCUMENT_SET: u32 = 0;
pub const OT_SELECT_DOCUMENT_UPDATE: u32 = 1;
pub const OT_SELECT_DOCUMENT_RESET: u32 = 2;
pub const OT_SELECT_VIEWPORT_SET: u32 = 3;
pub const OT_SELECT_VIEWPORT_UPDATE: u32 = 4;
pub const OT_SELECT_VIEWPORT_RESET: u32 = 5;
pub const OT_SELECTION_CELL: u32 = 0;
pub const OT_SELECTION_WORD: u32 = 1;
pub const OT_SELECTION_LINE: u32 = 2;
pub const OT_SELECTION_OCCUPANCY_CELL: u32 = 0;
pub const OT_SELECTION_OCCUPANCY_BOUNDARY: u32 = 1;
pub const OT_EDITOR_POSITION_CURSOR: u32 = 0;
pub const OT_EDITOR_POSITION_NEXT_WORD: u32 = 1;
pub const OT_EDITOR_POSITION_PREV_WORD: u32 = 2;
pub const OT_EDITOR_POSITION_EOL: u32 = 3;
pub const OT_EDITOR_POSITION_VISUAL_SOL: u32 = 4;
pub const OT_EDITOR_POSITION_VISUAL_EOL: u32 = 5;
pub const OT_IMAGE_FIT: u32 = 0;
pub const OT_IMAGE_COVER: u32 = 1;
pub const OT_IMAGE_FILL: u32 = 2;
pub const OT_IMAGE_PROTOCOL_AUTO: u32 = 0;
pub const OT_IMAGE_PROTOCOL_KITTY: u32 = 1;
pub const OT_IMAGE_PROTOCOL_SIXEL: u32 = 2;
pub const OT_IMAGE_PROTOCOL_BLOCKS: u32 = 3;
pub const OT_IMAGE_DRAW_SOURCE_WIDTH: u32 = 1;
pub const OT_IMAGE_DRAW_SOURCE_HEIGHT: u32 = 2;
pub const OT_TEXT_VIEW_WRAP_WIDTH: u32 = 0;
pub const OT_TEXT_VIEW_WRAP_MODE: u32 = 1;
pub const OT_TEXT_VIEW_FIRST_LINE_OFFSET: u32 = 2;
pub const OT_TEXT_VIEW_TAB_INDICATOR: u32 = 3;
pub const OT_TEXT_VIEW_TRUNCATE: u32 = 4;
pub const OT_TEXT_REPLACEMENT_COUNT_MAX: u32 = 256;
pub const OT_TEXT_REPLACEMENT_CHUNKS_MAX: u32 = 4096;
pub const OT_TEXT_REPLACEMENT_BYTES_MAX: u32 = 4194304;
pub const OT_TEXT_REPLACEMENT_URL_BYTES_MAX: u32 = 1048576;
pub const OT_BUFFER_TEXT_BYTES_MAX: u32 = 65536;
pub const OT_BUFFER_TEXT_HAS_BACKGROUND: u32 = 1;
pub const OT_BUFFER_DRAW_CLEAR: u32 = 0;
pub const OT_BUFFER_DRAW_FILL: u32 = 1;
pub const OT_BUFFER_DRAW_TEXT: u32 = 2;
pub const OT_BUFFER_DRAW_CELL: u32 = 3;
pub const OT_BUFFER_DRAW_CELL_BLEND: u32 = 4;
pub const OT_BUFFER_DRAW_CHAR: u32 = 5;
pub const OT_BUFFER_DRAW_BOX: u32 = 6;
pub const OT_BUFFER_DRAW_COMPOSE: u32 = 7;
pub const OT_BUFFER_DRAW_RESPECT_ALPHA: u32 = 8;
pub const OT_BUFFER_DRAW_HAS_BACKGROUND: u32 = 1;
pub const OT_BUFFER_DRAW_HAS_SOURCE_WIDTH: u32 = 2;
pub const OT_BUFFER_DRAW_HAS_SOURCE_HEIGHT: u32 = 4;
pub const OT_BUFFER_STACK_DEPTH_MAX: u32 = 256;
pub const OT_BUFFER_STACK_GET_OPACITY: u32 = 0;
pub const OT_BUFFER_STACK_PUSH_SCISSOR: u32 = 1;
pub const OT_BUFFER_STACK_POP_SCISSOR: u32 = 2;
pub const OT_BUFFER_STACK_CLEAR_SCISSORS: u32 = 3;
pub const OT_BUFFER_STACK_PUSH_OPACITY: u32 = 4;
pub const OT_BUFFER_STACK_POP_OPACITY: u32 = 5;
pub const OT_BUFFER_STACK_CLEAR_OPACITY: u32 = 6;
pub const OT_BUFFER_GRID_INNER: u32 = 1;
pub const OT_BUFFER_GRID_OUTER: u32 = 2;
pub const OT_SESSION_CONTROL_PACKET_BYTES: u32 = 4096;
pub const OT_TERMINAL_ALTERNATE_SCREEN: u32 = 1;
pub const OT_TERMINAL_MOUSE: u32 = 2;
pub const OT_TERMINAL_MOUSE_MOVEMENT: u32 = 4;
pub const OT_TERMINAL_CLEAR_ON_CLOSE: u32 = 8;
pub const OT_CONTROL_CAPABILITY_RESPONSE: u32 = 1;
pub const OT_CONTROL_TITLE: u32 = 2;
pub const OT_CONTROL_MOUSE: u32 = 3;
pub const OT_CONTROL_KITTY_KEYBOARD_FLAGS: u32 = 4;
pub const OT_CONTROL_RESTORE_MODES: u32 = 5;
pub const OT_CONTROL_QUERY_PIXEL_RESOLUTION: u32 = 6;
pub const OT_CONTROL_QUERY_THEME_COLORS: u32 = 7;
pub const OT_CONTROL_CURSOR: u32 = 8;
pub const OT_CONTROL_RESET_BACKGROUND: u32 = 9;
pub const OT_CONTROL_PALETTE_QUERY: u32 = 10;
pub const OT_CURSOR_POSITION: u32 = 1;
pub const OT_CURSOR_STYLE: u32 = 2;
pub const OT_CURSOR_BLINKING: u32 = 4;
pub const OT_CURSOR_COLOR: u32 = 8;
pub const OT_CURSOR_MOUSE_POINTER: u32 = 16;
pub const OT_CAP_KITTY_KEYBOARD: u32 = 1;
pub const OT_CAP_KITTY_GRAPHICS: u32 = 2;
pub const OT_CAP_RGB: u32 = 4;
pub const OT_CAP_ANSI256: u32 = 8;
pub const OT_CAP_SGR_PIXELS: u32 = 16;
pub const OT_CAP_COLOR_SCHEME_UPDATES: u32 = 32;
pub const OT_CAP_EXPLICIT_WIDTH: u32 = 64;
pub const OT_CAP_SCALED_TEXT: u32 = 128;
pub const OT_CAP_SIXEL: u32 = 256;
pub const OT_CAP_FOCUS_TRACKING: u32 = 512;
pub const OT_CAP_SYNC: u32 = 1024;
pub const OT_CAP_BRACKETED_PASTE: u32 = 2048;
pub const OT_CAP_HYPERLINKS: u32 = 4096;
pub const OT_CAP_OSC52: u32 = 8192;
pub const OT_CAP_NOTIFICATIONS: u32 = 16384;
pub const OT_CAP_EXPLICIT_CURSOR_POSITIONING: u32 = 32768;
pub const OT_CAP_REMOTE: u32 = 65536;
pub const OT_TERMINAL_UNINITIALIZED: u32 = 0;
pub const OT_TERMINAL_SETTING_UP: u32 = 1;
pub const OT_TERMINAL_ACTIVE: u32 = 2;
pub const OT_TERMINAL_SUSPENDING: u32 = 3;
pub const OT_TERMINAL_SUSPENDED: u32 = 4;
pub const OT_TERMINAL_RESUMING: u32 = 5;
pub const OT_TERMINAL_CLOSING: u32 = 6;
pub const OT_TERMINAL_RESTORED: u32 = 7;
pub const OT_TERMINAL_FAILED: u32 = 8;
pub const OT_TERMINAL_CANCELLED: u32 = 9;
pub const OT_PUMP_IDLE: u32 = 0;
pub const OT_PUMP_AGAIN: u32 = 1;
pub const OT_PUMP_OUTPUT_PENDING: u32 = 2;
pub const OT_PUMP_WAIT_UNTIL: u32 = 3;
pub const OT_PUMP_CLOSED: u32 = 4;
pub const OT_DIAGNOSTIC_MESSAGE_BYTES: u32 = 4096;
pub const OT_DIAGNOSTIC_TRUNCATED: u32 = 1;
#[cfg(test)]
fn constants() -> Vec<u32> {
    vec![
        OT_CONTEXT_ABI_VERSION as u32,
        OT_OK as u32,
        OT_INVALID_ARGUMENT as u32,
        OT_UNSUPPORTED_VERSION as u32,
        OT_OUT_OF_MEMORY as u32,
        OT_WRONG_THREAD as u32,
        OT_INTERNAL_ERROR as u32,
        OT_CONTEXT_BUSY as u32,
        OT_WRONG_CONTEXT as u32,
        OT_WRONG_KIND as u32,
        OT_STALE_HANDLE as u32,
        OT_WRONG_SESSION as u32,
        OT_OUTPUT_BACKPRESSURE as u32,
        OT_SESSION_CLOSED as u32,
        OT_OUTPUT_BUSY as u32,
        OT_STALE_OUTPUT as u32,
        OT_OUTPUT_FAILED as u32,
        OT_OBJECT_LIMIT as u32,
        OT_RENDERER_ATTACHED as u32,
        OT_RENDERER_NOT_ATTACHED as u32,
        OT_INVALID_PHASE as u32,
        OT_CONTROL_PACKET_LIMIT as u32,
        OT_LEASE_LIMIT as u32,
        OT_LEASE_BYTES_LIMIT as u32,
        OT_STALE_LEASE as u32,
        OT_UNSUPPORTED_RESOURCE as u32,
        OT_STALE_FRAME as u32,
        OT_LAYOUT_LIMIT as u32,
        OT_FRAME_BUSY as u32,
        OT_FRAME_REQUEST_LIMIT as u32,
        OT_SCENE_ROOT as u32,
        OT_SCENE_BOX as u32,
        OT_SCENE_TEXT as u32,
        OT_SCENE_SLIDER as u32,
        OT_SCENE_ARROW as u32,
        OT_SCENE_EDITOR as u32,
        OT_SCENE_CUSTOM as u32,
        OT_SCENE_TEXT_VIEW as u32,
        OT_SCENE_IMAGE as u32,
        OT_SCENE_WRAP_NONE as u32,
        OT_SCENE_WRAP_CHAR as u32,
        OT_SCENE_WRAP_WORD as u32,
        OT_STYLE_ENUM as u32,
        OT_STYLE_FLOAT as u32,
        OT_STYLE_VALUE as u32,
        OT_STYLE_BORDER as u32,
        OT_STYLE_DIMENSION as u32,
        OT_STYLE_BORDER_WIDTH as u32,
        OT_STYLE_FLAGS_NONE as u32,
        OT_STYLE_DISABLE_FLEX_SHRINK as u32,
        OT_STYLE_ENUM_DIRECTION as u32,
        OT_STYLE_ENUM_FLEX_DIRECTION as u32,
        OT_STYLE_ENUM_JUSTIFY_CONTENT as u32,
        OT_STYLE_ENUM_ALIGN_CONTENT as u32,
        OT_STYLE_ENUM_ALIGN_ITEMS as u32,
        OT_STYLE_ENUM_ALIGN_SELF as u32,
        OT_STYLE_ENUM_POSITION_TYPE as u32,
        OT_STYLE_ENUM_FLEX_WRAP as u32,
        OT_STYLE_ENUM_OVERFLOW as u32,
        OT_STYLE_ENUM_DISPLAY as u32,
        OT_STYLE_ENUM_BOX_SIZING as u32,
        OT_STYLE_FLOAT_FLEX as u32,
        OT_STYLE_FLOAT_FLEX_GROW as u32,
        OT_STYLE_FLOAT_FLEX_SHRINK as u32,
        OT_STYLE_FLOAT_ASPECT_RATIO as u32,
        OT_STYLE_VALUE_WIDTH as u32,
        OT_STYLE_VALUE_HEIGHT as u32,
        OT_STYLE_VALUE_MIN_WIDTH as u32,
        OT_STYLE_VALUE_MIN_HEIGHT as u32,
        OT_STYLE_VALUE_MAX_WIDTH as u32,
        OT_STYLE_VALUE_MAX_HEIGHT as u32,
        OT_STYLE_VALUE_FLEX_BASIS as u32,
        OT_STYLE_VALUE_MARGIN as u32,
        OT_STYLE_VALUE_PADDING as u32,
        OT_STYLE_VALUE_POSITION as u32,
        OT_STYLE_VALUE_GAP as u32,
        OT_DIMENSION_WIDTH as u32,
        OT_DIMENSION_HEIGHT as u32,
        OT_UNIT_UNDEFINED as u32,
        OT_UNIT_POINT as u32,
        OT_UNIT_PERCENT as u32,
        OT_UNIT_AUTO as u32,
        OT_EDGE_NONE as u32,
        OT_EDGE_LEFT as u32,
        OT_EDGE_TOP as u32,
        OT_EDGE_RIGHT as u32,
        OT_EDGE_BOTTOM as u32,
        OT_EDGE_START as u32,
        OT_EDGE_END as u32,
        OT_EDGE_HORIZONTAL as u32,
        OT_EDGE_VERTICAL as u32,
        OT_EDGE_ALL as u32,
        OT_GUTTER_COLUMN as u32,
        OT_GUTTER_ROW as u32,
        OT_GUTTER_ALL as u32,
        OT_DIRECTION_INHERIT as u32,
        OT_DIRECTION_LTR as u32,
        OT_DIRECTION_RTL as u32,
        OT_FLEX_DIRECTION_COLUMN as u32,
        OT_FLEX_DIRECTION_COLUMN_REVERSE as u32,
        OT_FLEX_DIRECTION_ROW as u32,
        OT_FLEX_DIRECTION_ROW_REVERSE as u32,
        OT_JUSTIFY_FLEX_START as u32,
        OT_JUSTIFY_CENTER as u32,
        OT_JUSTIFY_FLEX_END as u32,
        OT_JUSTIFY_SPACE_BETWEEN as u32,
        OT_JUSTIFY_SPACE_AROUND as u32,
        OT_JUSTIFY_SPACE_EVENLY as u32,
        OT_ALIGN_AUTO as u32,
        OT_ALIGN_FLEX_START as u32,
        OT_ALIGN_CENTER as u32,
        OT_ALIGN_FLEX_END as u32,
        OT_ALIGN_STRETCH as u32,
        OT_ALIGN_BASELINE as u32,
        OT_ALIGN_SPACE_BETWEEN as u32,
        OT_ALIGN_SPACE_AROUND as u32,
        OT_ALIGN_SPACE_EVENLY as u32,
        OT_POSITION_STATIC as u32,
        OT_POSITION_RELATIVE as u32,
        OT_POSITION_ABSOLUTE as u32,
        OT_FLEX_WRAP_NONE as u32,
        OT_FLEX_WRAP_WRAP as u32,
        OT_FLEX_WRAP_REVERSE as u32,
        OT_OVERFLOW_VISIBLE as u32,
        OT_OVERFLOW_HIDDEN as u32,
        OT_OVERFLOW_SCROLL as u32,
        OT_DISPLAY_FLEX as u32,
        OT_DISPLAY_NONE as u32,
        OT_BOX_SIZING_BORDER_BOX as u32,
        OT_BOX_SIZING_CONTENT_BOX as u32,
        OT_STYLE_ENUM_DIRECTION_MAX as u32,
        OT_STYLE_ENUM_FLEX_DIRECTION_MAX as u32,
        OT_STYLE_ENUM_JUSTIFY_CONTENT_MAX as u32,
        OT_STYLE_ENUM_ALIGN_CONTENT_MAX as u32,
        OT_STYLE_ENUM_ALIGN_ITEMS_MAX as u32,
        OT_STYLE_ENUM_ALIGN_SELF_MAX as u32,
        OT_STYLE_ENUM_POSITION_TYPE_MAX as u32,
        OT_STYLE_ENUM_FLEX_WRAP_MAX as u32,
        OT_STYLE_ENUM_OVERFLOW_MAX as u32,
        OT_STYLE_ENUM_DISPLAY_MAX as u32,
        OT_STYLE_ENUM_BOX_SIZING_MAX as u32,
        OT_MEASURE_UNDEFINED as u32,
        OT_MEASURE_EXACTLY as u32,
        OT_MEASURE_AT_MOST as u32,
        OT_LAYOUT_PUBLIC as u32,
        OT_LAYOUT_YOGA as u32,
        OT_LAYOUT_PAINT as u32,
        OT_BORDER_NONE as u32,
        OT_BORDER_LEFT as u32,
        OT_BORDER_BOTTOM as u32,
        OT_BORDER_RIGHT as u32,
        OT_BORDER_TOP as u32,
        OT_BORDER_ALL as u32,
        OT_BORDER_SINGLE as u32,
        OT_BORDER_DOUBLE as u32,
        OT_BORDER_ROUNDED as u32,
        OT_BORDER_HEAVY as u32,
        OT_COLOR_RGB as u32,
        OT_COLOR_INDEXED as u32,
        OT_COLOR_DEFAULT as u32,
        OT_COLOR_CHANNEL_MASK as u32,
        OT_COLOR_META_SHIFT as u32,
        OT_SCENE_TEXT_SELECTION_RESET as u32,
        OT_SCENE_TEXT_SELECTION_SET as u32,
        OT_SCENE_TEXT_SELECTION_UPDATE as u32,
        OT_SCENE_TEXT_SELECTION_CELL as u32,
        OT_SCENE_TEXT_SELECTION_WORD as u32,
        OT_SCENE_TEXT_SELECTION_LINE as u32,
        OT_SCENE_TEXT_SELECTION_BACKGROUND as u32,
        OT_SCENE_TEXT_SELECTION_FOREGROUND as u32,
        OT_SCENE_TEXT_FOREGROUND as u32,
        OT_SCENE_TEXT_BACKGROUND as u32,
        OT_SCENE_TEXT_LINK as u32,
        OT_SCENE_MUTATIONS_MAX as u32,
        OT_SCENE_HOOK_UPDATE as u32,
        OT_SCENE_HOOK_RESIZE as u32,
        OT_SCENE_HOOK_LAYOUT_CHANGED as u32,
        OT_SCENE_HOOK_RENDER_BEFORE as u32,
        OT_SCENE_HOOK_RENDER_AFTER as u32,
        OT_SCENE_HOOK_RENDER_SELF as u32,
        OT_SCENE_HOOK_IDLE_UPDATE as u32,
        OT_SCENE_HOOK_RESUME_NATIVE_TEXT as u32,
        OT_SCENE_FRAME_DONE as u32,
        OT_SCENE_FRAME_UPDATE as u32,
        OT_SCENE_FRAME_RESIZE as u32,
        OT_SCENE_FRAME_LAYOUT_CHANGED as u32,
        OT_SCENE_FRAME_RENDER_BEFORE as u32,
        OT_SCENE_FRAME_RENDER_AFTER as u32,
        OT_SCENE_FRAME_YIELD as u32,
        OT_SCENE_FRAME_RENDER_SELF as u32,
        OT_SCENE_GEOMETRY_PAINT as u32,
        OT_SCENE_GEOMETRY_PUBLIC as u32,
        OT_SCENE_UPDATE_SKIP as u32,
        OT_SCENE_UPDATE_APPLY as u32,
        OT_SESSION_OPEN as u32,
        OT_SESSION_CLOSING as u32,
        OT_SESSION_CLOSED_STATE as u32,
        OT_SESSION_FAILED as u32,
        OT_SESSION_CANCELLED_STATE as u32,
        OT_SESSION_REMOTE_AUTO as u32,
        OT_SESSION_REMOTE_LOCAL as u32,
        OT_SESSION_REMOTE_REMOTE as u32,
        OT_SESSION_ENV_ENTRIES_MAX as u32,
        OT_SESSION_ENV_BYTES_MAX as u32,
        OT_RENDER_PRESENTED as u32,
        OT_RENDER_PENDING as u32,
        OT_RENDER_SKIPPED as u32,
        OT_RENDER_FAILED as u32,
        OT_SESSION_BUFFER_CURRENT as u32,
        OT_SESSION_BUFFER_NEXT as u32,
        OT_WIDTH_METHOD_WCWIDTH as u32,
        OT_WIDTH_METHOD_UNICODE as u32,
        OT_WIDTH_METHOD_NO_ZWJ as u32,
        OT_WIDTH_METHOD_UNICODE_WIDE as u32,
        OT_BUFFER_RESPECT_ALPHA as u32,
        OT_EMBEDDED_TERMINAL_INVALIDATE as u32,
        OT_EMBEDDED_TERMINAL_SCROLL as u32,
        OT_EMBEDDED_TERMINAL_CLEAR_SELECTION as u32,
        OT_EDIT_CURSOR_CHANGED as u32,
        OT_EDIT_CONTENT_CHANGED as u32,
        OT_EDIT_HISTORY_CURSOR_CHANGED as u32,
        OT_EDIT_DELETE_FORWARD as u32,
        OT_EDIT_BACKSPACE as u32,
        OT_EDIT_NEW_LINE as u32,
        OT_EDIT_DELETE_LINE as u32,
        OT_EDIT_MOVE_LEFT as u32,
        OT_EDIT_MOVE_RIGHT as u32,
        OT_EDIT_MOVE_UP as u32,
        OT_EDIT_MOVE_DOWN as u32,
        OT_EDIT_GOTO_LINE as u32,
        OT_EDIT_CURSOR_OFFSET as u32,
        OT_EDIT_CLEAR as u32,
        OT_EDIT_CLEAR_HISTORY as u32,
        OT_EDIT_DEBUG_ROPE as u32,
        OT_EDIT_POSITION_CURSOR as u32,
        OT_EDIT_POSITION_NEXT_WORD as u32,
        OT_EDIT_POSITION_PREV_WORD as u32,
        OT_EDIT_POSITION_EOL as u32,
        OT_EDIT_POSITION_OFFSET as u32,
        OT_EDIT_POSITION_COORDS as u32,
        OT_EDIT_POSITION_LINE_START as u32,
        OT_EDITOR_STYLE_FOREGROUND as u32,
        OT_EDITOR_STYLE_BACKGROUND as u32,
        OT_EDITOR_STYLE_ATTRIBUTES as u32,
        OT_EDIT_HIGHLIGHT_ADD_LINE as u32,
        OT_EDIT_HIGHLIGHT_ADD_RANGE as u32,
        OT_EDIT_HIGHLIGHT_REMOVE_REF as u32,
        OT_EDIT_HIGHLIGHT_CLEAR_LINE as u32,
        OT_EDIT_HIGHLIGHT_CLEAR_ALL as u32,
        OT_EDITOR_MOVE_UP as u32,
        OT_EDITOR_MOVE_DOWN as u32,
        OT_EDITOR_GOTO_LINE_END as u32,
        OT_EDITOR_DELETE_SELECTION as u32,
        OT_EDITOR_CURSOR_OFFSET as u32,
        OT_EDITOR_WRAP_MODE as u32,
        OT_EDITOR_TAB_INDICATOR as u32,
        OT_EDITOR_SELECT_SET as u32,
        OT_EDITOR_SELECT_UPDATE as u32,
        OT_EDITOR_SELECT_RESET as u32,
        OT_EDITOR_SELECT_LOCAL as u32,
        OT_EDITOR_SELECT_LOCAL_UPDATE as u32,
        OT_EDITOR_SELECT_LOCAL_RESET as u32,
        OT_EDITOR_SELECT_CELL as u32,
        OT_EDITOR_SELECT_OCCUPANCY as u32,
        OT_EDITOR_SELECT_INCLUSIVE as u32,
        OT_EDITOR_SELECT_COLORS as u32,
        OT_SELECT_DOCUMENT_SET as u32,
        OT_SELECT_DOCUMENT_UPDATE as u32,
        OT_SELECT_DOCUMENT_RESET as u32,
        OT_SELECT_VIEWPORT_SET as u32,
        OT_SELECT_VIEWPORT_UPDATE as u32,
        OT_SELECT_VIEWPORT_RESET as u32,
        OT_SELECTION_CELL as u32,
        OT_SELECTION_WORD as u32,
        OT_SELECTION_LINE as u32,
        OT_SELECTION_OCCUPANCY_CELL as u32,
        OT_SELECTION_OCCUPANCY_BOUNDARY as u32,
        OT_EDITOR_POSITION_CURSOR as u32,
        OT_EDITOR_POSITION_NEXT_WORD as u32,
        OT_EDITOR_POSITION_PREV_WORD as u32,
        OT_EDITOR_POSITION_EOL as u32,
        OT_EDITOR_POSITION_VISUAL_SOL as u32,
        OT_EDITOR_POSITION_VISUAL_EOL as u32,
        OT_IMAGE_FIT as u32,
        OT_IMAGE_COVER as u32,
        OT_IMAGE_FILL as u32,
        OT_IMAGE_PROTOCOL_AUTO as u32,
        OT_IMAGE_PROTOCOL_KITTY as u32,
        OT_IMAGE_PROTOCOL_SIXEL as u32,
        OT_IMAGE_PROTOCOL_BLOCKS as u32,
        OT_IMAGE_DRAW_SOURCE_WIDTH as u32,
        OT_IMAGE_DRAW_SOURCE_HEIGHT as u32,
        OT_TEXT_VIEW_WRAP_WIDTH as u32,
        OT_TEXT_VIEW_WRAP_MODE as u32,
        OT_TEXT_VIEW_FIRST_LINE_OFFSET as u32,
        OT_TEXT_VIEW_TAB_INDICATOR as u32,
        OT_TEXT_VIEW_TRUNCATE as u32,
        OT_TEXT_REPLACEMENT_COUNT_MAX as u32,
        OT_TEXT_REPLACEMENT_CHUNKS_MAX as u32,
        OT_TEXT_REPLACEMENT_BYTES_MAX as u32,
        OT_TEXT_REPLACEMENT_URL_BYTES_MAX as u32,
        OT_BUFFER_TEXT_BYTES_MAX as u32,
        OT_BUFFER_TEXT_HAS_BACKGROUND as u32,
        OT_BUFFER_DRAW_CLEAR as u32,
        OT_BUFFER_DRAW_FILL as u32,
        OT_BUFFER_DRAW_TEXT as u32,
        OT_BUFFER_DRAW_CELL as u32,
        OT_BUFFER_DRAW_CELL_BLEND as u32,
        OT_BUFFER_DRAW_CHAR as u32,
        OT_BUFFER_DRAW_BOX as u32,
        OT_BUFFER_DRAW_COMPOSE as u32,
        OT_BUFFER_DRAW_RESPECT_ALPHA as u32,
        OT_BUFFER_DRAW_HAS_BACKGROUND as u32,
        OT_BUFFER_DRAW_HAS_SOURCE_WIDTH as u32,
        OT_BUFFER_DRAW_HAS_SOURCE_HEIGHT as u32,
        OT_BUFFER_STACK_DEPTH_MAX as u32,
        OT_BUFFER_STACK_GET_OPACITY as u32,
        OT_BUFFER_STACK_PUSH_SCISSOR as u32,
        OT_BUFFER_STACK_POP_SCISSOR as u32,
        OT_BUFFER_STACK_CLEAR_SCISSORS as u32,
        OT_BUFFER_STACK_PUSH_OPACITY as u32,
        OT_BUFFER_STACK_POP_OPACITY as u32,
        OT_BUFFER_STACK_CLEAR_OPACITY as u32,
        OT_BUFFER_GRID_INNER as u32,
        OT_BUFFER_GRID_OUTER as u32,
        OT_SESSION_CONTROL_PACKET_BYTES as u32,
        OT_TERMINAL_ALTERNATE_SCREEN as u32,
        OT_TERMINAL_MOUSE as u32,
        OT_TERMINAL_MOUSE_MOVEMENT as u32,
        OT_TERMINAL_CLEAR_ON_CLOSE as u32,
        OT_CONTROL_CAPABILITY_RESPONSE as u32,
        OT_CONTROL_TITLE as u32,
        OT_CONTROL_MOUSE as u32,
        OT_CONTROL_KITTY_KEYBOARD_FLAGS as u32,
        OT_CONTROL_RESTORE_MODES as u32,
        OT_CONTROL_QUERY_PIXEL_RESOLUTION as u32,
        OT_CONTROL_QUERY_THEME_COLORS as u32,
        OT_CONTROL_CURSOR as u32,
        OT_CONTROL_RESET_BACKGROUND as u32,
        OT_CONTROL_PALETTE_QUERY as u32,
        OT_CURSOR_POSITION as u32,
        OT_CURSOR_STYLE as u32,
        OT_CURSOR_BLINKING as u32,
        OT_CURSOR_COLOR as u32,
        OT_CURSOR_MOUSE_POINTER as u32,
        OT_CAP_KITTY_KEYBOARD as u32,
        OT_CAP_KITTY_GRAPHICS as u32,
        OT_CAP_RGB as u32,
        OT_CAP_ANSI256 as u32,
        OT_CAP_SGR_PIXELS as u32,
        OT_CAP_COLOR_SCHEME_UPDATES as u32,
        OT_CAP_EXPLICIT_WIDTH as u32,
        OT_CAP_SCALED_TEXT as u32,
        OT_CAP_SIXEL as u32,
        OT_CAP_FOCUS_TRACKING as u32,
        OT_CAP_SYNC as u32,
        OT_CAP_BRACKETED_PASTE as u32,
        OT_CAP_HYPERLINKS as u32,
        OT_CAP_OSC52 as u32,
        OT_CAP_NOTIFICATIONS as u32,
        OT_CAP_EXPLICIT_CURSOR_POSITIONING as u32,
        OT_CAP_REMOTE as u32,
        OT_TERMINAL_UNINITIALIZED as u32,
        OT_TERMINAL_SETTING_UP as u32,
        OT_TERMINAL_ACTIVE as u32,
        OT_TERMINAL_SUSPENDING as u32,
        OT_TERMINAL_SUSPENDED as u32,
        OT_TERMINAL_RESUMING as u32,
        OT_TERMINAL_CLOSING as u32,
        OT_TERMINAL_RESTORED as u32,
        OT_TERMINAL_FAILED as u32,
        OT_TERMINAL_CANCELLED as u32,
        OT_PUMP_IDLE as u32,
        OT_PUMP_AGAIN as u32,
        OT_PUMP_OUTPUT_PENDING as u32,
        OT_PUMP_WAIT_UNTIL as u32,
        OT_PUMP_CLOSED as u32,
        OT_DIAGNOSTIC_MESSAGE_BYTES as u32,
        OT_DIAGNOSTIC_TRUNCATED as u32,
    ]
}
